### ISSUE TITLE
[BUG]: Error when reload page after search anything

### ISSUE THREAD

**Issue by marcelorafaelfeil** [simranlotey/react-news-app#1]
Hi @simranlotey,

I was reviewing your project and I found a bug after to search anything and the refresh the page. As you can see in the video below, an error page is being displayed to the user.

https://github.com/simranlotey/react-news-app/assets/12664500/ab0ed6b5-9925-4754-b49f-70202c314f14

**Comment by marcelorafaelfeil** [comment]
I took the liberty to fix that problem for you: https://github.com/simranlotey/react-news-app/pull/2
☺️

**Comment by simranlotey** [comment]
@marcelorafaelfeil I saw this bug yesterday. I thought I would fix it today. When I started doing it today, you already fixed it. Thanks for it.😉👍
