### ISSUE TITLE
[Bug]: Close button is not showing in in mobile devices

### ISSUE THREAD

**Issue by basavarajakj** [simranlotey/react-news-app#5]
When i click on navigation bar Hemberger menu navigation screen is opening In order to close Hemberger menu is showing could you please add close icon to it

![image](https://github.com/simranlotey/react-news-app/assets/97227305/9f89ea79-dfb7-4267-802f-dc0f1ddf9862)

**Comment by simranlotey** [comment]
OK, Good idea👍
